version: "3.8"

services:
  app:
    build: .
    container_name: note_analytics_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@db:5432/notes_db"
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: note_analytics_db
    restart: always
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d notes_db"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  pg_data:
