FROM python:3.12

WORKDIR /backend

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . /backend


CMD ["sh", "-c", "coverage run -m pytest --asyncio-mode=auto && coverage report"]
